-- File 06: 25 distractor tables in analytics, generated by one DO block.
-- Every table has the SAME generic shape: id SERIAL PK, name, status, created_at,
-- plus 20 rows of near-identical data — so schema linking / glossary extraction /
-- term recurrence get genuinely hard, and generic column names recur heavily.
--
-- One deliberate trap: the distractor "stores" gives any bare "store_id" column
-- elsewhere (staging.stg_returns, staging.stg_web_events) an inference target that
-- is NOT the real dimension (sales.dim_stores).

SET client_min_messages = WARNING;

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'assets', 'tags', 'labels', 'batches', 'buckets',
        'snapshots', 'tokens', 'widgets', 'gadgets', 'portals',
        'queues', 'topics', 'threads', 'messages', 'alerts',
        'notices', 'tasks', 'jobs', 'runs', 'stages',
        'states', 'phases', 'marks', 'zones', 'stores'
    ] LOOP
        EXECUTE format(
            'CREATE TABLE analytics.%I ('
            || 'id SERIAL PRIMARY KEY, '
            || 'name VARCHAR(80) NOT NULL, '
            || 'status VARCHAR(24), '
            || 'created_at TIMESTAMPTZ NOT NULL DEFAULT now())', t);
        EXECUTE format(
            'INSERT INTO analytics.%I (name, status) '
            || 'SELECT %L || '' '' || i, (ARRAY[''active'',''archived''])[1 + i %% 2] '
            || 'FROM generate_series(1, 20) i', t, t);
    END LOOP;
END $$;
